import { Component, signal } from '@angular/core';
import { MaterialModule } from '../../material.module';
import { EducationCardComponent } from "../../components/education-card/education-card.component";
import { Education } from '../../models/Education';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-about',
  imports: [MaterialModule, EducationCardComponent, RouterLink],
  templateUrl: './about.component.html',
  styleUrl: './about.component.scss',
})
export class AboutComponent {
  readonly panelOpenState = signal(false);
  certs: Education[] = [
    {
      title: 'Grado Superior - Desarrollo de aplicaciones web',
      subtitle: '',
      institution: 'MEDAC',
      location: 'Albacete',
      period: 'Sept 2023 - Jun 2025',
      image: 'cerebro.png',
      icon: 'location_on',
      tags: [
        'JavaScript',
        'Typescript',
        'Java',
        'PHP',
        'MySQL',
        'MongoDB',
        'Administración de sistemas',
        'HTML5',
        'CSS3',
      ],
    },
    {
      title: 'Grado Medio Sistemas microinformáticos y redes',
      subtitle: '',
      institution: 'IES Leonardo Da Vinci',
      location: 'Albacete',
      period: 'Sept 2014 - Jun 2016',
      image: 'insignia.png',
      icon: 'location_on',
      tags: [
        'Instalación y configuración',
        'Mantenimiento',
        'Soporte técnico',
        'Seguridad informática',
        'Redes',
        'Administración Typescriptde sistemas',
        'Ofimática',
        'Montaje y reparación',
        'HTML5',
        'CSS3',
      ],
    },
  ];

  otros: Education[] = [
    {
      title: 'Laravel',
      subtitle: '',
      institution: 'Antonio Martín León',
      location: 'OpenWebinars',
      period: '5 Horas',
      image: 'laravel.png',
      icon: 'location_on',
      tags: ['Php', 'Laravel', 'Eloquent'],
    },
    {
      title: 'Angular',
      subtitle: '',
      institution: 'Manuel Agudo',
      location: 'Youtube',
      period: '5 Horas',
      image: 'angular.png',
      icon: 'location_on',
      tags: ['AngularJS'],
    },
    {
      title: 'Fundamentos de React',
      subtitle: '',
      institution: 'Manuel Agudo',
      location: 'OpenWebinars',
      period: '6 Horas',
      image: 'react.png',
      icon: 'location_on',
      tags: ['React'],
    },
    {
      title: 'Javascript - Nivel JUNIOR',
      subtitle: '',
      institution: 'Soy Dalto',
      location: 'Youtube',
      period: '10 Horas',
      image: 'javascript.png',
      icon: 'location_on',
      tags: ['Javascript'],
    },
    {
      title: 'Javascript - Nivel MID',
      subtitle: '',
      institution: 'Soy Dalto',
      location: 'Youtube',
      period: '8 Horas',
      image: 'javascript.png',
      icon: 'location_on',
      tags: ['Javascript'],
    },
    {
      title: 'Javascript - Nivel MASTER',
      subtitle: '',
      institution: 'Soy Dalto',
      location: 'Youtube',
      period: '10 Horas',
      image: 'javascript.png',
      icon: 'location_on',
      tags: ['Javascript'],
    },
    {
      title: 'Python',
      subtitle: '',
      institution: 'Soy Dalto',
      location: 'Youtube',
      period: '8 Horas',
      image: 'python.png',
      icon: 'location_on',
      tags: ['Python'],
    },
    {
      title: 'Curso GIT y GITHUB',
      subtitle: '',
      institution: 'Midudev',
      location: 'Youtube',
      period: '4 Horas',
      image: 'git.png',
      icon: 'location_on',
      tags: ['GIT', 'GITHUB'],
    },
    {
      title: 'HTML y CSS Completo',
      subtitle: '',
      institution: 'Soy Dalto',
      location: 'Youtube',
      period: '24 Horas',
      image: 'marcas.png',
      icon: 'location_on',
      tags: ['HTML5', 'CSS3'],
    },
    {
      title: 'Inglés',
      subtitle: '',
      institution: 'Sr Richard',
      location: 'Udemy',
      period: '25 Horas',
      image: 'ingles.png',
      icon: 'location_on',
      tags: ['Inglés'],
    },
  ];
}