import { Component, signal } from '@angular/core';
import { MaterialModule } from '../../material.module';
import { EducationCardComponent } from "../../components/education-card/education-card.component";
import { Education } from '../../models/Education';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-about',
  imports: [MaterialModule, EducationCardComponent, RouterLink],
  templateUrl: './about.component.html',
  styleUrl: './about.component.scss',
})
export class AboutComponent {
  readonly panelOpenState = signal(false);
  certs: Education[] = [
    {
      title: 'Grado Superior - Desarrollo de aplicaciones web',
      subtitle: '',
      institution: 'MEDAC',
      location: 'Albacete',
      period: 'Sept 2023 - Jun 2025',
      image: 'cerebro.png',
      icon: 'location_on',
      tags: [
        'Java',
        'JavaScript',
        'Typescript',
        'PHP',
        'MySQL',
        'MongoDB',
        'AngularJS',
        'React',
        'HTML5',
        'CSS3',
      ],
    },
    {
      title: 'Grado Medio Sistemas microinformáticos y redes',
      subtitle: '',
      institution: 'IES Leonardo Da Vinci',
      location: 'Albacete',
      period: 'Sept 2014 - Jun 2016',
      image: 'insignia.png',
      icon: 'location_on',
      tags: [
        'Instalación y configuración',
        'Mantenimiento',
        'Soporte técnico',
        'Seguridad informática',
        'Redes',
        'Ofimática',
        'Montaje y reparación',
        'HTML5',
        'CSS3',
      ],
    },
  ];

  otros: Education[] = [
    {
      title: 'API REST con Java y Spring Boot',
      subtitle: '',
      institution: 'Marcel Bosh',
      location: 'Udemy',
      period: '16 horas',
      image: 'spring.png',
      icon: 'location_on',
      tags: ['Java', 'Spring', 'Hibernate', 'JWT', 'JUnit', 'Lombook', 'Mockito', 'Postman'],
    },
    {
      title: 'Laravel',
      subtitle: '',
      institution: 'Antonio Martín León',
      location: 'OpenWebinars',
      period: '5 horas',
      image: 'laravel.png',
      icon: 'location_on',
      tags: ['Php', 'Laravel', 'Eloquent', 'Postman'],
    },
    {
      title: 'Angular',
      subtitle: '',
      institution: 'Manuel Agudo',
      location: 'Youtube',
      period: '5 horas',
      image: 'angular.png',
      icon: 'location_on',
      tags: ['AngularJS'],
    },
    {
      title: 'Fundamentos de React',
      subtitle: '',
      institution: 'Manuel Agudo',
      location: 'OpenWebinars',
      period: '6 horas',
      image: 'react.png',
      icon: 'location_on',
      tags: ['React'],
    },
    {
      title: 'Javascript - Niveles JUNIOR, MID y MASTER',
      subtitle: '',
      institution: 'Soy Dalto',
      location: 'Youtube',
      period: '28 horas',
      image: 'javascript.png',
      icon: 'location_on',
      tags: ['Javascript'],
    },
    {
      title: 'Python',
      subtitle: '',
      institution: 'Soy Dalto',
      location: 'Youtube',
      period: '8 horas',
      image: 'python.png',
      icon: 'location_on',
      tags: ['Python'],
    },
    {
      title: 'Curso GIT y GITHUB',
      subtitle: '',
      institution: 'Midudev',
      location: 'Youtube',
      period: '4 horas',
      image: 'git.png',
      icon: 'location_on',
      tags: ['GIT', 'GITHUB'],
    },
    {
      title: 'HTML y CSS Completo',
      subtitle: '',
      institution: 'Soy Dalto',
      location: 'Youtube',
      period: '24 horas',
      image: 'marcas.png',
      icon: 'location_on',
      tags: ['HTML5', 'CSS3'],
    },
    {
      title: 'Inglés',
      subtitle: '',
      institution: 'Francis Carlisle',
      location: 'Udemy',
      period: '25 horas',
      image: 'ingles.png',
      icon: 'location_on',
      tags: ['Inglés'],
    },
  ];
}